name: my first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello RishiKushi"
      - name: print bye
        run: echo "Bye"
